version: '3.8'

services:
  app:
    build: .
    container_name: ustatop_app
    restart: always
    ports:
      - "${API_PORT}:3001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm run start:dev

  db:
    image: postgres:17
    container_name: ustatop_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-example}
      POSTGRES_DB: ${POSTGRES_DB:-nestdb}
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ustatop_redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  pgdata:
